const images = {
  First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
  Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
  Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
  Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
  Account_created: require('./LottieAnimation/Accountcreated.json'),
  Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
  Languageanimation: require('./LottieAnimation/languageanimation.json'),
  Plumber_Animation: require('./LottieAnimation/Plumber.json'),
  Clining_Animation: require('./LottieAnimation/Clining.json'),
  Home_Security: require('./LottieAnimation/HomeSecurity.json'),
  Electric_Service: require('./LottieAnimation/ElectricService.json'),
  AC_Animation: require('./LottieAnimation/ACAnimation.json'),
  FanAc_Image: require('./LottieAnimation/FanAcImage.json'),
  Fan_Image: require('./LottieAnimation/docs acceptance.json'),
  Color_picker_image: require('./colorpicker.png'),
  Google_image: require('./googleicon.png'),
  Creditcard: require('./credit-card.png'),
  Paypal: require('./paypal.png'),
  phonepay: require('./phonepay.png'),
  GooglePay: require('./google-pay.png'),
  App_logo: require('./one_fifty.png'),
  UXdEsigner_one: require('./Designer.png'),
  User_image_one_profile: require('./Designer.png'),
  Chat_image_one: require('./ninghty.png'),
  Chat_image_five: require('./ninghty.png'),
  Chat_image_six: require('./ninghty.png'),
  Chat_image_saven: require('./sixty.png'),
  SerViceImage_One: require('./ninghty.png'),
  Fan_Service_image_1: require('./ninghty.png'),
  Fan_Service_image_2: require('./ninghty.png'),
  Fan_Service_image_3: require('./ninghty.png'),
  Fan_Service_image_4: require('./ninghty.png'),
  cleaning: require('./ninghty.png'),
  Computer_service: require('./ninghty.png'),
  Notification_one: require('./hundred.png'),
  Notification_two: require('./hundred.png'),
  ManageImg: require('./Manage.png'),
  CleanImg: require('./Cleanimg.png'),
  FanImg: require('./Fanimg.png'),
  // Ac: require('./LottieAnimation/ac.json'),
  clean: require('./Clean.png'),
  Repair: require('./Repair.png'),
  Fan: require('./Fan.png'),
  Ac: require('./AC.png'),
  app_logo: require('./logo.png'),
  message: require('./message.png'),
  confirmed: require('./confirm.png'),
  Scan: require('./Scan.png'),
  waiting: require('./waiting.png'),
  rejected: require('./Rejected.png'),
  invited: require('./notinvited.png'),
  failed: require('./failed.png'),
  google: require('./Google.png'),
  iconone: require('./iconone.png'),
  iconthree: require('./iconthree.png'),
  Maskgroup: require('./Maskgroup.png'),
  image27: require('./image27.png'),

  // SearchImg: require('./Search.png'),
  // statusbar: require('./Statusbar.png'),
};
export default images;
