import {StyleSheet} from 'react-native';
import {Fonts, SF, SH, SW, Colors, widthPercent} from '../../utils';
const HomeTabStyle = StyleSheet.create({
  // import {StyleSheet} from 'react-native';
  // import {Colors, SH, SW, SF, Fonts, widthPercent} from '../../utils';

  // export default HomeTabStyle = Colors =>
  FImgViewHome: {
    flexDirection: 'column', // Display items in a column
    //alignItems: 'center', // Align items at the center horizontally
  },
  flatlistimgHome: {
    width: SW(50), // Adjust width as needed
    height: SH(50), // Adjust height as needed
  },
  textOnehome: {
    marginTop: SH(5), // Adjust margin as needed
    fontSize: SF(15), // Adjust font size as needed
    color: 'black', // Adjust color as needed
    fontFamily: Fonts.Poppins_Medium, // Adjust font family as needed
  },

  btnstyle: {
    height: SH(35),
    width: SW(95),
    backgroundColor: Colors.darkBlue,
    marginLeft: SF(20),
    borderTopLeftRadius: SF(20),
    borderBottomRightRadius: SF(20),
  },
  homebtntext: {
    textAlign: 'center',
    color: 'white',
    marginTop: 3,
    alignItems: 'center',
  },
  MinViewScreen: {
    height: '100%',
    backgroundColor: Colors.white_text_color,
    width: '100%',
  },
  MinViewAllContent: {
    paddingHorizontal: SH(10),
  },
  BgColorView: {
    padding: SH(20),
    // margin: SH(5),
    justifyContent: 'center',
    borderBottomRightRadius: SF(40),
    borderBottomLeftRadius: SF(40),

    backgroundColor: Colors.darkBlue,
  
  },
  BgColorTransparent: {
    backgroundColor: 'transparent',
    borderWidth: 0,
    fontSize: SF(17),
    color: Colors.black_text_color,
    // paddingTop: SH(7),
    borderTopLeftRadius: 20,
    height: SH(50),
    shadowOffset: {
      width: 0,
      height: Platform.OS === 'ios' ? 0 : 0,
    },
    shadowOpacity: 0.58,
    shadowRadius: Platform.OS === 'ios' ? 0 : 0,
    elevation: Platform.OS === 'ios' ? 0 : 0,
  },
  FlexrowSearchView: {
    backgroundColor: Colors.white_text_color,
    flexDirection: 'row',
    alignItems: 'center',

    // justifyContent: 'space-between',
    marginHorizontal: SW(20),
    borderTopLeftRadius: SH(20),
    borderBottomRightRadius: SH(20),
    // height: SH(55),
    width: '90%',

    // paddingRight: SH(20),
  },
  InputSpaceView: {
    width: widthPercent(79),
    // justifyContent: 'center',
    // margin: SW(0),
  },
  IconViewStyles: {
    width: widthPercent(20),
  },
  PlaceHolderStyles: {
    color: Colors.black_text_color,
    fontFamily: Fonts.Poppins_Medium,
    fontSize: SF(15),
  },
  BoxSmallViewFlatList: {
    width: SW(80),
    backgroundColor: Colors.ghost_white_color,
    paddingVertical: SH(20),
    borderRadius: SH(20),
    position: 'relative',
    marginRight: SH(17),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  BoxSmallViewSecondColor: {
    width: SW(80),
    backgroundColor: Colors.theme_background_han_Purple,
    paddingVertical: SH(20),
    borderRadius: SH(20),
    position: 'relative',
    marginRight: SH(17),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  TextStylesBox: {
    color: Colors.theme_background_han_Purple,
    fontSize: SF(14),
    fontFamily: Fonts.Poppins_Medium,
    textAlign: 'center',
  },
  TextStylesBoxColorWhite: {
    color: Colors.white_text_color,
    fontSize: SF(14),
    fontFamily: Fonts.Poppins_Medium,
    textAlign: 'center',
  },
  IconCenter: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: Colors.theme_bg_second_lavender_color,
    width: SH(50),
    height: SH(60),
    borderRadius: SH(200),
  },
  CenterIcobn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  Flatliststyles: {
    paddingHorizontal: SH(20),
  },
  OurServiceFlatList: {
    paddingHorizontal: SH(10),
  },
  PostionTopSpace: {
    // paddingHorizontal: SH(20),
    height: SH(350),
    justifyContent: 'center',
    width: '95%',
    marginHorizontal: '2.5%',
    // marginLeft: SH(5),
    alignItems: 'center',
    // marginTop: SH(-70),
    backgroundColor: 'white',
    borderRadius: SH(25),
    borderColor: 'black',
    borderWidth: 0.8,
  },
  PostionCalender: {
    // paddingHorizontal: SH(20),
    height: SH(350),
    justifyContent: 'center',
    width: '95%',
    marginHorizontal: '2.5%',
    // marginLeft: SH(5),
    alignItems: 'center',
    // marginTop: SH(-70),
    backgroundColor: Colors.theme_background_han_Purple,
    borderRadius: SH(25),
    borderColor: 'black',
    borderWidth: 0.8,
    marginBottom: SH(10),
  },
  unreadboxview: {
    // paddingHorizontal: SH(20),
    height: SH(350),
    justifyContent: 'center',
    width: '95%',
    marginHorizontal: '2.5%',
    // marginLeft: SH(5),
    // alignItems: 'center',
    // marginTop: SH(-70),
    backgroundColor: 'lightgrey',
    // borderRadius: SH(25),
    // borderColor: 'black',
    // borderWidth: 0.8,
  },
  FlexRowTwoText: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: SH(20),
  },
  OurServiceTextStyle: {
    fontFamily: Fonts.Poppins_Medium,
    color: Colors.black_text_color,
    fontSize: SF(17),
  },
  ViewAllTextStyles: {
    fontFamily: Fonts.Poppins_Medium,
    color: Colors.black_text_color,
    fontSize: SF(17),
  },
  OurServiceMinView: {
    backgroundColor: Colors.ghost_white_color,
    width: widthPercent(45),
    padding: SH(10),
    marginRight: SH(15),
    borderRadius: SH(10),
    marginBottom: SH(30),
  },
  AcServiceText: {
    fontFamily: Fonts.Poppins_Medium,
    color: Colors.black_text_color,
    fontSize: SF(17),
    width: widthPercent(20),
  },
  AcImageStyles: {
    height: SH(53),
    width: SW(103),
  },
  LottieStyles: {
    width: SW(80),
  },
  ImageStyles: {
    width: SW(50),
    height: SH(80),
    borderRadius: SH(1),
  },
  OurServiceImageStyles: {
    width: SW(50),
    height: SH(120),
    borderRadius: SH(10),
    justifyContent: 'flex-end',
    paddingHorizontal: SW(70),
    marginLeft: SH(30),
    marginTop: SW(20),
  },
  BoxViewsNews: {
    backgroundColor: Colors.theme_bg_second_lavender_color,
    marginRight: SH(20),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderRadius: SH(10),
    width: widthPercent(80),
    padding: SH(10),
  },
  ImageViewWidth: {
    width: '33%',
  },
  TextViewWidth: {
    width: '67%',
  },
  NewsTextStyles: {
    color: Colors.theme_background_han_Purple,
    fontFamily: Fonts.Poppins_Medium,
    fontSize: SF(17),
    fontWeight: '700',
  },
  NewsTextSmall: {
    color: Colors.black_text_color,
    fontFamily: Fonts.Poppins_Medium,
    fontSize: SF(14),
  },
  MinContentView: {
    paddingTop: SH(20),
    backgroundColor: Colors.theme_bg_second_lavender_color,
  },
  OrderHistoryMinView: {
    marginTop: SH(-70),
    backgroundColor: Colors.white_text_color,
    borderTopLeftRadius: SH(35),
    padding: SH(20),
    paddingTop: SH(25),
    borderTopRightRadius: SH(35),
  },
  HomeTabStyles: {
    backgroundColor: Colors.white_text_color,
    height: '100%',
  },
  OurServiceText: {
    color: Colors.theme_background_han_Purple,
    fontFamily: Fonts.Poppins_Medium,
    fontSize: SF(20),
  },
  NewsServicesText: {
    fontFamily: Fonts.Poppins_Medium,
    color: Colors.black_text_color,
    fontSize: SF(17),
    paddingLeft: SH(15),
  },
  statusstyle: {
    height: SH(30),
    width: SW(20),
    padding: SH(5),
    marginTop: SH(10),
    margin: SW(2),
  },
  LoginButton: {
    height: SF(40),
    width: SW(160),
    backgroundColor: 'black',
    borderRadius: SH(10),
    margin: SH(50),
  },
  textstyle: {
    color: 'white',
    fontSize: SF(15),
    textAlign: 'center',
    justifyContent: 'center',
    margin: SW(5),
  },
  viewtextstyle: {
    fontSize: SF(20),

    // color: Colors.theme_background_han_Purple,
    color: 'black',
    padding: SW(5),
    marginTop: SH(70),
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
  },
  poaterstyle: {
    height: SH(170),
    width: SW(180),
    marginTop: SH(10),
  },
  createdstyle: {
    fontSize: SF(19),
    fontWeight: '500',
    color: 'black',
    paddingRight: SH(240),
    margin: SH(10),
  },
  ActiveButton: {
    height: SH(30),
    width: SW(100),
    backgroundColor: 'black',
    borderRadius: SH(10),
    marginLeft: SH(25),
  },
  topuptextstyle: {
    fontSize: SF(15),
    fontWeight: '400',
    color: 'black',
    paddingRight: SH(5),
    margin: SW(10),
    marginTop: SH(50),
  },
  catigoryheading: {
    fontSize: SF(17),
    color: 'black',
    fontWeight: '700',
    paddingLeft: SW(20),
  },
  seemoreheading: {
    fontSize: SF(15),
    color: Colors.darkBlue,
    fontWeight: '700',
    marginLeft: 'auto',
    paddingLeft: SW(15),
  },
  boxoneview: {
    height: SH(90),
    width: SW(360),
    backgroundColor: Colors.white_text_color,
    marginHorizontal: '2%',
    flexDirection: 'row',
    borderTopLeftRadius: SF(15),
    borderBottomRightRadius: SF(15),
    margin: SH(5),
    // shadowOpacity: 5,
    elevation: 10,
  },
  ImgView: {
    height: SH(90),
    width: SW(60),
    justifyContent: 'center',
    // backgroundColor: 'red',
  },
  recentConversationImage: {
    height: SH(50),
    width: SW(45),
    margin: '15%',
  },
  maintextView: {
    height: SH(90),
    width: SW(250),
    // backgroundColor: 'gray',
    // marginHorizontal: '1%',
  },
  lasttextView: {
    height: SH(90),
    width: SW(50),
    // backgroundColor: 'purple',
    flexDirection: 'column',
    justifyContent: 'center',
    paddingHorizontal: '1%',
  },
  juststyle: {
    fontSize: SF(8),
    color: Colors.gray_text_color,
    paddingVertical: '20%',
    // margin: SW(2),
  },
  iconStyle: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginHorizontal: '15%',
  },

  boxsecondview: {
    height: SH(130),
    width: SW(360),
    backgroundColor: Colors.white_text_color,
    marginHorizontal: '2%',
    // flexDirection: 'row',
    borderTopLeftRadius: SF(15),
    borderBottomRightRadius: SF(15),
    margin: SH(5),
    // shadowOpacity: 5,
    elevation: 10,
  },

  btntext: {
    color: 'white',
    fontSize: SF(12),
    fontWeight: '600',
    textAlign: 'center',
    marginTop: SH(7),
  },

  juststylesec: {
    fontSize: SF(8),
    color: Colors.gray_text_color,
    // paddingHorizontal: '4%',
    marginTop: SH(50),
    justifyContent: 'space-evenly',
  },
  iconStylesec: {
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',
    marginHorizontal: '9%',
  },
  btnview: {
    flexDirection: 'row',
    height: SH(20),
    width: SW(230),
    justifyContent: 'center',
    alignItems: 'center',
    alignContent: 'center',

    marginLeft: SW(50),
  },
  maincontainer: {
    height: SH(60),
    width: '90%',
    backgroundColor: Colors.light_gray_text_color,
    margintop: SH(0),
    justifyContent: 'center',
    alignContent: 'center',
    alignItems: 'center',
    marginLeft: SW(20),
    flexDirection: 'row',
    // borderRadius: SF(10),
    borderTopLeftRadius: SF(20),
    borderBottomRightRadius: SF(20),
    borderColor: Colors.gray_text_color,
    // borderWidth: 0.5,
  },
  availablestyle: {
    color: 'black',
    fontWeight: '400',
    textAlign: 'center',
    paddingTop: SH(1),
    paddingLeft: SF(30),
  },
  invitationstyle: {
    color: 'black',
    fontWeight: '400',
    //textAlign: 'center',
    paddingLeft: 30,
  },
  topbtnview: {
    height: SH(38),
    width: '24%',
    backgroundColor: Colors.darkBlue,
    marginLeft: 'auto',
    marginVertical: SH(30),
    marginHorizontal: SW(10),
    //borderRadius: 10,
    borderTopLeftRadius: SF(20),
    borderBottomRightRadius: SF(20),
    borderColor: Colors.theme_background_han_Purple,
    borderWidth: 0.5,
  },
  draftview: {
    height: SH(40),
    width: '30%',
    backgroundColor: '#7966FE',
    marginLeft: 'auto',
    // marginVertical: SH(30),
    marginHorizontal: SW(20),
    borderRadius: 10,
    borderColor: Colors.theme_background_han_Purple,
    borderWidth: 0.5,
  },
  topstyle: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: SH(6),
  },
  createdView: {
    height: SH(50),
    width: '90%',
    backgroundColor: 'lightgray',
    margin: 20,
    flexDirection: 'row',
    borderRadius: SF(10),
  },
  createdstyle: {
    color: 'black',
    paddingTop: SH(15),
    paddingLeft: SW(5),
    fontWeight: '500',
  },
  sortbystyle: {
    marginLeft: 'auto',
    margin: SW(10),
    color: '#6c25f7',
    fontWeight: '500',
  },
  SundayViewTop: {
    height: SH(220),
    width: '90%',
    backgroundColor: 'red',
    margin: 20,
    flexDirection: 'row',
    borderRadius: SF(10),
    borderColor: Colors.theme_background_han_Purple,
    borderWidth: 0.5,
  },
  SundayView: {
    height: SH(220),
    width: '90%',
    backgroundColor: '#ebe7fc',
    margin: 20,
    flexDirection: 'row',
    borderRadius: SF(10),
    borderColor: Colors.theme_background_han_Purple,
    borderWidth: 0.5,
  },
  SundayStyle: {
    color: 'black',
    fontWeight: '500',
    textAlign: 'center',
    paddingTop: SH(20),
    paddingLeft: 30,
  },
  birthdayStyle: {
    paddingTop: SH(2),
    paddingLeft: 30,
    // marginLeft: 'auto',
    // margin: SW(10),
    color: '#6c25f7',
    fontWeight: '600',
  },
  officeimg: {
    height: SH(130),
    width: '40%',
    marginLeft: 'auto',
  },
  iconstyle: {
    height: SH(20),
    width: SW(30),
    flexDirection: 'row',
    marginLeft: SW(20),
  },
  imgview: {
    height: SH(100),
    width: '90%',

    flexDirection: 'row',
    backgroundColor: 'gray',
  },
});
export default HomeTabStyle;
