import {StyleSheet} from 'react-native';
import {Fonts, SF, SH, SW, Colors} from '../../utils';
const MessagingStyles = StyleSheet.create({
  BackgroundWhite: {
    // backgroundColor: Colors.light_gray_text_color,
    backgroundColor: 'white',
  },
  whilistminbody: {
    width: '100%',
    // marginTop: '1%',
    height: '100%',
  },
  ScrollViewTestHe: {
    height: 'auto',
    width: '100%',
  },
  OnlineView: {
    height: SH(30),
    // width: SW(350),
    // backgroundColor: 'gray',
    justifyContent: 'center',
    alignContent: 'center',
    margin: SW(10),
  },
  friendstyle: {
    fontSize: 17,
    color: Colors.black_text_color,
    fontWeight: '700',
    paddingLeft: SW(4),
  },
  itemBox: {
    height: SH(60),
    width: SW(50),
    backgroundColor: Colors.chinese_silver,
    justifyContent: 'center',
    alignItems: 'center',
    margin: SW(5),
    borderRadius: SF(30),
  },
  itemText: {
    margin: SW(2),

    justifyContent: 'space-evenly',
    marginLeft: SW(10),
  },
  whatsNewItem: {
    height: SH(120),
    width: SW(100),
    backgroundColor: Colors.chinese_silver,
    justifyContent: 'center',
    alignItems: 'center',
    margin: SW(5),
    borderRadius: SF(30),
  },
  recentconversationtem: {
    // height: SH(60),
    // width: SW(370),
    // backgroundColor: Colors.chinese_silver,
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: SW(2),
    borderRadius: SF(3),
    flexDirection: 'row',
    padding: 10,
    // borderBottomWidth: 0.3,
    borderTopWidth: 0.5,
    borderWdthColor: 'gray',
  },
  recentconversationtemTop: {
    // height: SH(60),
    // width: SW(370),
    // backgroundColor: Colors.chinese_silver,
    justifyContent: 'space-between',
    alignItems: 'center',
    //margin: SW(1),
    borderRadius: SF(3),
    flexDirection: 'row',
    padding: 10,
    // borderBottomWidth: 0.3,
    borderTopWidth: 0.5,
    borderWdthColor: 'gray',
  },
  recentConversationImage: {
    height: SH(48),
    width: SW(40),
    marginLeft: SW(10),
  },
  //   ImgView: {
  //     height: SH(50),
  //     width: SW(60),
  //     backgroundColor: 'red',
  //   },
  FImgView: {
    height: SH(120),
    // height: '40%',
    width: SW(150),
  },
  FImgViewHome: {
    height: '30%',
    //height: SH(120),
    // height: '40%',
    //width: SW(150),
  },
  FImgViewHomeTop: {
    height: '50%',
    backgroundColor: 'green',
  },
  flatlistimg: {
    // height: '100%',
    width: '100%',
    // marginLeft: 'auto',
  },
  flatlistimgHome: {
    width: '100%',
  },
  flatlistimgHomeTop: {
    width: '100%',
  },
  whatsNewTextfirst: {
    fontSize: SF(17),
    width: '90%',
    fontWeight: '700',
    color: Colors.black_text_color,
    paddingLeft: SW(20),
    backgroundColor: 'transparent',
  },
  whatsNewText: {
    // height: SH(40),
    width: SW(240),
    paddingLeft: SW(4),
    // backgroundColor: 'green',
  },
  //   whatsNewdate: {
  //     height: SH(50),
  //     width: SW(90),
  //     backgroundColor: 'yellow',
  //   },
  watsnewMainview: {
    height: SH(200),
    width: SW(115),
    backgroundColor: Colors.chinese_silver,
    justifyContent: 'space-between',
    alignItems: 'center',
    margin: SW(5),
    borderRadius: SF(3),
    flexDirection: 'row',
    borderTopRightRadius: SF(20),
    borderTopLeftRadius: SF(20),
    //padding: 10,
  },
  NewItemView: {
    height: SH(160),
    marginTop: SH(30),
    width: SW(115),
    borderTopRightRadius: SF(20),
    borderTopLeftRadius: SF(20),
    backgroundColor: Colors.theme_background_han_Purple,

    // justifyContent: 'space-between',
    // alignItems: 'center',
    marginRight: SW(15),
    borderRadius: SF(3),
    // flexDirection: 'row',
    // padding: 10,
  },
  whatsNewTextstyle: {
    fontSize: SF(17),
    color: Colors.black_text_color,
  },
  searchView: {
    marginLeft: SW(10),
  },
  CreateEventView: {
    flexDirection: 'row',
    paddingVertical: SH(10),
    backgroundColor: Colors.theme_bg_second_lavender_color,
  },
  imagepickerview: {
    height: SH(200),
    width: '90%',
    borderColor: 'lightgray',
    justifyContent: 'center',
    alignContent: 'center',
    margin: SW(20),
    borderTopLeftRadius: SF(30),
    borderBottomRightRadius: SF(30),

    borderWidth: 1,
  },
  flatlistView: {
    flexDirection: 'row',
    width: '4%',
    backgroundColor: 'green',
  },
  flatlistimg: {
    width: '100%',
    height: SH(200),
  },
});
export default MessagingStyles;
