const images = {
  First_Swiper: require('./LottieAnimation/FirstSwiper.json'),
  Two_Swiper: require('./LottieAnimation/TwoSwiper.json'),
  Three_Swiper: require('./LottieAnimation/ThreeSwiper.json'),
  Splash_Swiper: require('./LottieAnimation/SplashScreen.json'),
  Account_created: require('./LottieAnimation/Accountcreated.json'),
  Reviewsimage_screen: require('./LottieAnimation/Reviewsimage.json'),
  Languageanimation: require('./LottieAnimation/languageanimation.json'),
  Plumber_Animation: require('./LottieAnimation/Plumber.json'),
  Clining_Animation: require('./LottieAnimation/Clining.json'),
  Home_Security: require('./LottieAnimation/HomeSecurity.json'),
  Electric_Service: require('./LottieAnimation/ElectricService.json'),
  AC_Animation: require('./LottieAnimation/ACAnimation.json'),
  FanAc_Image: require('./LottieAnimation/FanAcImage.json'),
  Fan_Image: require('./LottieAnimation/docs acceptance.json'),
  Color_picker_image: require('./colorpicker.png'),
  Google_image: require('./googleicon.png'),
  Creditcard: require('./credit-card.png'),
  Paypal: require('./paypal.png'),
  phonepay: require('./phonepay.png'),
  GooglePay: require('./google-pay.png'),
  App_logo: require('./one_fifty.png'),
  UXdEsigner_one: require('./Designer.png'),
  User_image_one_profile: require('./Designer.png'),
  Chat_image_one: require('./ninghty.png'),
  Chat_image_five: require('./ninghty.png'),
  Chat_image_six: require('./ninghty.png'),
  Chat_image_saven: require('./sixty.png'),
  SerViceImage_One: require('./ninghty.png'),
  Fan_Service_image_1: require('./ninghty.png'),
  Fan_Service_image_2: require('./ninghty.png'),
  Fan_Service_image_3: require('./ninghty.png'),
  Fan_Service_image_4: require('./ninghty.png'),
  cleaning: require('./ninghty.png'),
  Computer_service: require('./ninghty.png'),
  Notification_one: require('./hundred.png'),
  Notification_two: require('./hundred.png'),
  ManageImg: require('./Manage.png'),
  CleanImg: require('./Cleanimg.png'),
  FanImg: require('./Fanimg.png'),
  // Ac: require('./LottieAnimation/ac.json'),
  clean: require('./Clean.png'),
  Repair: require('./Repair.png'),
  Fan: require('./Fan.png'),
  Ac: require('./AC.png'),
  app_logo: require('./logo.png'),
  eventlogo1: require('./eventlogo1.png'),
  message: require('./message.png'),
  confirmed: require('./confirm.png'),
  Scan: require('./Scan.png'),
  waiting: require('./waiting.png'),
  rejected: require('./Rejected.png'),
  invited: require('./notinvited.png'),
  failed: require('./failed.png'),
  google: require('./Google.png'),
  mapimg: require('./mapimg.png'),
  officeimg: require('./officeimg.png'),
  backgroundimgone: require('./backgroundimgone.jpg'),
  backgroundimgtwo: require('./backgroundimgtwo.jpg'),
  backgroundimgthree: require('./backgroundimgthree.jpg'),
  backgroundimgfour: require('./backgroundimgfour.jpg'),
  backgroundimgfifth: require('./backgroundimgfifth.jpg'),
  icon4: require('./icon4.png'),
  iconone: require('./iconone.png'),
  iconthree: require('./iconthree.png'),
  iconthree: require('./iconthree.png'),
  halalogo: require('./hallaLogo.png'),
  employee: require('./employee-of-the-month 1.png'),
  cardone: require('./cardone.png'),
  Group: require('./Group.png'),
  wallbackground2: require('./wallbackground2.png'),
  engLang: require('./engLang.png'),
  arabLang: require('./arabLang.png'),
  wallpaper: require('./wallpaper.png'),
  wallpaper2: require('./wallpaper2.png'),
  wallpaper3: require('./wallpaper3.png'),
  blueiconone: require('./blueiconone.png'),
  gridicons_add: require('./gridicons_add.png'),
  Vectortwo: require('./Vectortwo.png'),
  Rectangle: require('./Rectangle.png'),
  MaskgroupP: require('./MaskgroupP.png'),
  messagesicon: require('./messagesicon.png'),
  scanned: require('./scanned.png'),
  waitng: require('./waitng.png'),
  rejected: require('./rejectediconone.png'),
  notinivted: require('./notinivted.png'),
  Failedicon: require('./Failedicon.png'),
  AllDoneimg: require('./AllDoneimg.png'),
  success: require('./success.png'),
  backimg: require('./halla.png'),
  Doone: require('./Doone.png'),
  // MaskGroupPlus: require('./MaskGroupPlus.png'),

  // SearchImg: require('./Search.png'),
  // statusbar: require('./Statusbar.png'),
};
export default images;
