export const Colors = {
  theme_background_han_Purple: '#7966FE',
  theme_bg_second_lavender_color: '#ebe7fc',
  black_text_color: '#3c4452',
  gray_text_color: '#737272',
  light_gray_text_color: '#f2f2f4',
  white_text_color: '#ffffff',
  blue_color: 'blue',
  amber_color: '#FFC000',
  chinese_silver: '#C8C7C8',
  argent_color: '#C2C0C0',
  ghost_white_color: '#f8f9fc',
  spanish_pink_color: '#F5B9BD',
  spanish_pink_color: '#F5B9BD',
  sandy_tan_color: '#f8d2ba',
  sandy_tan_color: '#fadcc8',
  peach_orange: '#f4aa76',
  diamond_color: '#c1e3f4',
  pale_lavender: '#DCC7F8',
  pale_lavender: '#DCC7F8',
  blue_jeans_color: '#52b2fd',
  light_yellow: '#fef7d6',
  wageningen_green: '#299D35',
  darkBlue: '#293170',
  bluish: '#24638B',
  silver: '#BD9956',
};
export default Colors;
